### ISSUE TITLE
Replace musicmetadata with music-metadata

### ISSUE THREAD

**Issue by Borewit** [mycoboco/canary#23]
You are using musicmetadata as module to scan for metadata. Looks like this one is no longer maintained. Maybe you can give music-metadata a try? It will likely improve performance and stability, plus it supports more audio files and more metadata.

**Comment by mycoboco** [comment]
I'm very glad to hear of `music-metadata`. Your PR has been merged and I'll open an issue if any issue to be fixed or an idea for improvement exists.

Thanks.
