### ISSUE TITLE
check if works with new Music app on macOS

### ISSUE THREAD

**Issue by mycoboco** [mycoboco/canary#29]
The new Music app on macOS is reported not to play songs served from `canary`.

**Comment by yopming** [comment]
It works with Music 1.1.0.278 on macOS Big Sur beta 10.

**Comment by mycoboco** [comment]
When using `avahi` for mdns module, there are cases where Apple Music fails to work with `canary`. This is because the `TXT` field for `avahi` and `dns-sd` is not correctly set, and fixed by 88b3f9fe4509eab14e39da79b24d3372b1aa19d1.
